let dbBackupTask = [
  {
    assigned: [1, 2, 3],
    category: "User Story",
    date: "2024-09-18",
    description: "Test 3",
    id: 1,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: false,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 1",
    user: 0,
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 2,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 2",
    user: 0,
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 3,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 3",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 4,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 4",
    user: 0,
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 5,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 5",
    user: "",
  },
  {
    assigned: [1, 2, 3, 4],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Welcome to Join. Here you find your default board. This board represents your project and contains four default lists: \"To Do\", \"In Progress\", \"Await feedback\" and \"Done\".",
    id: 6,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Find the board.",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "First read all tutorials.",
      },
    ],
    title: "Tutorial 1: Exploring Join",
    user: "",
  },
  {
    assigned: [10],
    category: "User Story",
    date: "2024-09-20",
    description: "In your join you will find 10 tasks and 10 contacts to try out. You can edit these, but the changes will be reset after you log in again. If you delete them, they are permanently removed from your join.",
    id: 7,
    priority: "urgent",
    status: "todo",
    title: "Tutorial 2: Sample Tasks and Contacts",
    user: "",
  },
  {
    category: "Technical Task",
    date: "2024-09-20",
    description: "You can edit your cards. Tasks can be moved from one phase to the next, edited under \"Edit\" and deleted under \"Delete\".",
    id: 8,
    priority: "low",
    status: "inprogress",
    subtasks: [
      {
        done: false,
        subId: 1,
        subTaskName: "Change the title of a task.",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Add an assignee to the task.",
      },
      {
        done: false,
        subId: 3,
        subTaskName: "Add yourself as a assignee to the task.",
      },
      {
        done: false,
        subId: 4,
        subTaskName: "Move a task to another stage.",
      },
      {
        done: false,
        subId: 5,
        subTaskName: "Delete a task.",
      },
    ],
    title: "Tutorial 3: Edit Cards",
    user: "",
  },
  {
    assigned: [4, 5, 6, 7, 8],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Cards represent individual tasks. Click the \"+\" button under the corresponding list to create a new card. To create new cards you can also go to the \"Add Task\" section. Enter the task details in the card, e.g. E.g. task name, description, due date, assignee, etc.",
    id: 9,
    priority: "medium",
    status: "awaitfeedback",
    subtasks: [
      {
        done: false,
        subId: 1,
        subTaskName: "Go to \"Add Task\" in the menu and add a new task.",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Add a task directly under \"In progress\".",
      },
    ],
    title: "Tutorial 4: Adding Cards",
    user: "",
  },
  {
    assigned: [7, 8, 9],
    category: "User Story",
    date: "2024-09-20",
    description: "You can add contacts to collaborate on your projects. Go to the \"Contacts\" section, click on \"New contact\", and fill in the required information. Once added, these contacts can be assigned tasks and they can interact with the tasks on the board.",
    id: 10,
    priority: "medium",
    status: "done",
    subtasks: [
      {
        done: false,
        subId: 1,
        subTaskName: "Go to \"Contacts\" in the menu and add a new contact.",
      },
      
    ],
    title: "Tutorial 5: Creating Contacts",
    user: "",
  },
];

let dbBackupContacts = [
  {
    color: "#01687E",
    email: "Renken@gmail.com",
    id: 1,
    initials: "SR",
    name: "Susanne Renken",
    phone: 1733963852,
  },
  {
    color: "#19FF82",
    email: "Schumacher@gmail.com",
    id: 2,
    initials: "LS",
    name: "Lars Schumacher",
    phone: 1734216923,
  },
  {
    color: "#ED4F01",
    email: "Kaljuzhin@gmail.com",
    id: 3,
    initials: "AK",
    name: "Alex Kaljuzhin",
    phone: 12341234,
  },
  {
    color: "#1C7B2B",
    email: "Ziegler@gmail.com",
    id: 4,
    initials: "BZ",
    name: "Benedikt Ziegler",
    phone: 12341234,
  },
  {
    color: "#523C5A",
    email: "Eisenberg@gmail.com",
    id: 5,
    initials: "DE",
    name: "David Eisenberg",
    phone: 12341234,
  },
  {
    color: "#59C248",
    email: "Mauer@gmail.com",
    id: 6,
    initials: "EM",
    name: "Emmanuel Mauer",
    phone: 12341234,
  },
  {
    color: "#BA6C74",
    email: "Bauer@gmail.com",
    id: 7,
    initials: "MB",
    name: "Marcel Bauer",
    phone: 12341234,
  },
  {
    color: "#130994",
    email: "Wolf@gmail.com",
    id: 8,
    initials: "TW",
    name: "Tatjana Wolf",
    phone: 12341234,
  },
  {
    color: "#2A3A33",
    email: "Bibi2@gmail.com",
    id: 9,
    initials: "BB",
    name: "Bianca Bremer",
    phone: 12341234,
  },
  {
    color: "#FD5B4F",
    email: "Kovac@gmail.com",
    id: 10,
    initials: "KK",
    name: "Kevin Kovac",
    phone: 12341234,
  },
];
