let dbBackupTask = [
  {
    assigned: [1, 2, 3],
    category: "User Story",
    date: "2024-09-18",
    description: "Test 3",
    id: 1,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: false,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 1",
    user: 0,
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 2,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 2",
    user: 0,
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 3,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 3",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 4,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 4",
    user: 0,
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 5,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 5",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 6,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 6",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 7,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 7",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 8,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 8",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 9,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 9",
    user: "",
  },
  {
    assigned: [1, 2, 3],
    category: "Technical Task",
    date: "2024-09-20",
    description: "Test 3",
    id: 10,
    priority: "low",
    status: "todo",
    subtasks: [
      {
        done: true,
        subId: 1,
        subTaskName: "Subtask Id 1",
      },
      {
        done: false,
        subId: 2,
        subTaskName: "Subtask Id 2",
      },
    ],
    title: "Task Id 10",
    user: "",
  },
];

let dbBackupContacts = [
  {
    color: "#01687E",
    email: "Renken@gmail.com",
    id: 1,
    initials: "SR",
    name: "Susanne Renken",
    phone: 1733963852,
  },
  {
    color: "#19FF82",
    email: "Schumacher@gmail.com",
    id: 2,
    initials: "LS",
    name: "Lars Schumacher",
    phone: 1734216923,
  },
  {
    color: "#ED4F01",
    email: "Kaljuzhin@gmail.com",
    id: 3,
    initials: "AK",
    name: "Alex Kaljuzhin",
    phone: 12341234,
  },
  {
    color: "#1C7B2B",
    email: "Ziegler@gmail.com",
    id: 4,
    initials: "BZ",
    name: "Benedikt Ziegler",
    phone: 12341234,
  },
  {
    color: "#523C5A",
    email: "Eisenberg@gmail.com",
    id: 5,
    initials: "DE",
    name: "David Eisenberg",
    phone: 12341234,
  },
  {
    color: "#59C248",
    email: "Mauer@gmail.com",
    id: 6,
    initials: "EM",
    name: "Emmanuel Mauer",
    phone: 12341234,
  },
  {
    color: "#BA6C74",
    email: "Bauer@gmail.com",
    id: 7,
    initials: "MB",
    name: "Marcel Bauer",
    phone: 12341234,
  },
  {
    color: "#130994",
    email: "Wolf@gmail.com",
    id: 8,
    initials: "TW",
    name: "Tatjana Wolf",
    phone: 12341234,
  },
  {
    color: "#2A3A33",
    email: "Bibi2@gmail.com",
    id: 9,
    initials: "BB",
    name: "Bianca Bremer",
    phone: 12341234,
  },
  {
    color: "#FD5B4F",
    email: "Kovac@gmail.com",
    id: 10,
    initials: "KK",
    name: "Kevin Kovac",
    phone: 12341234,
  },
];
